{
 "title": "Main dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "server", "query": "artillery-api" },
   {
    "name": "container",
    "query": "exchange-api-1, exchange-api-2, exchange-api-3, exchange-cadvisor-1, exchange-grafana-1, exchange-graphite-1,  exchange-nginx-1, exchange_bbox_1, -"
   }
  ]
 },
 "panels": [
  {
   "title": "Throughput and scenarios",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.$server.scenarioCounts.*)"
    },
    {
     "target": "alias(stats.gauges.$server.rps.count, 'Requests/sec')"
    }
   ]
  },
  {
   "title": "Requests state (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(sumSeries(stats.gauges.$server.errors.*), 'Errored')"
    },
    {
     "target": "alias(stats.gauges.$server.codes.200, 'Completed')"
    },
    {
     "target": "alias(stats.gauges.$server.pendingRequests, 'Pending')"
    },
    {
     "target": "alias(stats.gauges.$server.codes.429, 'Limited')"
    }
   ]
  },
  {
   "title": "Response time (client-side)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.max, 'Upper')"
    },
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.median, 'Median')"
    },
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.p95, 'p95')"
    },
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.p99, 'p99')"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.$container.cpu_cumulative_usage, 100)), 10000000000), 0.0001), 'CPU')"
    },
    {
     "target": "alias(asPercent(stats.gauges.cadvisor.$container.memory_working_set, 34359738368), 'Memory')"
    }
   ]
  },
  {
   "title": "Volumen Operado por Moneda",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.exchange-api.business.volume.*, 5)"
    }
   ]
  },
  {
   "title": "Neto Operado por Moneda",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.exchange-api.business.net.*, 5)"
    }
   ]
  }
 ]
}